[features]
seeds = false
[programs.devnet]
metaplex_anchor_nft = "2pMfEegDLqhSz6YsMcoD3oxgxJyGJbKq2jsBBdYh7PC4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/start.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/initialize.ts"
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create.ts"
gold = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/gold.ts"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mint.ts"